### PR TITLE
Suggestions for code readability and maintainability

### PR DESCRIPTION
**Pull request by wuletawwonte**
🏁 Checks
- [x] Unit test passes

### CODE REVIEW

**Review by Dagic-zewdu — COMMENTED** [review]
### Resolve the conflict

To ensure a seamless integration, please take a moment to address any conflicts that may be present. Resolving these conflicts will significantly enhance the code's readability and maintainability for future iterations. I'm eager to review the code once the conflicts have been effectively addressed. ☮️

**Comment by wuletawwonte** [comment]
@Dagic-zewdu 
The conflict occurred due to the previous code format merge. I will fix it now.

**Comment by wuletawwonte** [comment]
@Dagic-zewdu 
I have resolved the merge conflict. I think it is ready for a review now.

**Review by Dagic-zewdu — APPROVED** [review]
Hi @wuletawwonte  ,

## Wow, you did it 🎉 

Brilliant

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
